"""

Revision ID: bbc4cfa83846
Revises: 71c832f18bb1
Create Date: 2025-12-13 14:04:52.066810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc4cfa83846'
down_revision = '71c832f18bb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('batch_size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'batch_size')
    # ### end Alembic commands ###